import { useState, type FormEvent } from 'react'
import { Building2, KeyRound, LockKeyhole } from 'lucide-react'
import { bootstrapServer } from '../lib/api'
import { signIn } from '../lib/backend'
import { Field } from './common'

export function SetupScreen() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); setError(''); try { await bootstrapServer({ setupToken: String(data.get('setupToken') || ''), organizationName: 'ר.א.ם הנדסה', supabaseUrl: String(data.get('supabaseUrl') || ''), supabaseAnonKey: String(data.get('supabaseAnonKey') || ''), adminEmails: String(data.get('adminEmails') || '').split(',').map((value) => value.trim()).filter(Boolean), googleClientId: String(data.get('googleClientId') || ''), googleClientSecret: String(data.get('googleClientSecret') || ''), openaiApiKey: String(data.get('openaiApiKey') || ''), openaiModel: 'gpt-5.6-terra' }); setDone(true); setTimeout(() => window.location.reload(), 1300) } catch (e) { setError(e instanceof Error ? e.message : 'הגדרה נכשלה') } finally { setLoading(false) } }
  return <div className="auth-screen"><div className="auth-brand"><img src="/rameng-mark.svg" /><div><strong>ר.א.ם הנדסה</strong><span>מערכת ניהול ופיקוח פרויקטים</span></div></div><section className="setup-card"><div className="setup-intro"><span><Building2 /></span><h1>הגדרה ראשונית</h1><p>המערכת מוכנה. יש לחבר את חשבון Supabase החדש ואת שירותי Google. לאחר ההגדרה הראשונית, הכול ניתן לניהול ממסך מנהל המערכת.</p></div>{error && <div className="error-banner">{error}</div>}{done && <div className="success-banner">ההגדרה נשמרה. המערכת נטענת מחדש...</div>}<form className="form-grid" onSubmit={(e) => void submit(e)}><Field label="Cloudflare Setup Token" hint="הערך שהוגדר פעם אחת כ-ADMIN_SETUP_TOKEN ב-Worker"><input name="setupToken" type="password" required /></Field><Field label="Supabase Project URL"><input name="supabaseUrl" required placeholder="https://xxxxx.supabase.co" /></Field><Field label="Supabase anon key"><textarea name="supabaseAnonKey" rows={3} required /></Field><Field label="מייל מנהל ראשון"><input name="adminEmails" type="email" required /></Field><div className="setup-divider">Google ו-AI - אפשר גם אחר כך</div><Field label="Google OAuth Client ID"><input name="googleClientId" /></Field><Field label="Google OAuth Client Secret"><input name="googleClientSecret" type="password" /></Field><Field label="OpenAI API Key"><input name="openaiApiKey" type="password" /></Field><button className="primary setup-submit" disabled={loading}><KeyRound /> {loading ? 'שומר ומחבר...' : 'שמירת הגדרה ראשונית'}</button></form></section></div>
}

export function LoginScreen({ onSuccess }: { onSuccess: () => void }) {
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); setError(''); try { await signIn(String(data.get('email') || ''), String(data.get('password') || '')); onSuccess() } catch (e) { setError(e instanceof Error ? e.message : 'התחברות נכשלה') } finally { setLoading(false) } }
  return <div className="auth-screen"><div className="auth-brand"><img src="/rameng-mark.svg" /><div><strong>ר.א.ם הנדסה</strong><span>CRM · ניהול · פיקוח</span></div></div><section className="login-card"><span className="login-icon"><LockKeyhole /></span><h1>כניסה למערכת</h1><p>התחברות מאובטחת באמצעות Supabase Auth.</p>{error && <div className="error-banner">{error}</div>}<form className="form-grid" onSubmit={(e) => void submit(e)}><Field label="מייל"><input name="email" type="email" required autoComplete="email" /></Field><Field label="סיסמה"><input name="password" type="password" required autoComplete="current-password" /></Field><button className="primary login-submit" disabled={loading}>{loading ? 'מתחבר...' : 'כניסה'}</button></form></section></div>
}
