import { useState, type FormEvent } from 'react'
import { CalendarPlus, ExternalLink, FileText, RefreshCw, Upload } from 'lucide-react'
import { integrationsApi } from '../lib/api'
import { uploadFile } from '../lib/backend'
import type { CalendarEvent, FileRecord, Workspace } from '../types'
import { Chip, EmptyState, Field, Modal, dateTimeLabel, nowIso, uid } from './common'

export function CalendarPage({ workspace, setWorkspace }: { workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>> }) {
  const [adding, setAdding] = useState(false); const [syncing, setSyncing] = useState(false); const [error, setError] = useState('')
  const sorted = [...workspace.events].sort((a, b) => a.start.localeCompare(b.start))
  const sync = async () => { setSyncing(true); setError(''); try { const from = new Date(Date.now() - 30 * 86400000).toISOString(); const to = new Date(Date.now() + 180 * 86400000).toISOString(); const { items } = await integrationsApi.calendarEvents(from, to); setWorkspace((current) => { const localByGoogle = new Map(current.events.filter((item) => item.googleEventId).map((item) => [item.googleEventId, item])); const imported = items.map((item) => ({ id: localByGoogle.get(item.id)?.id || uid('event'), title: item.summary, start: item.start, end: item.end, location: item.location, googleEventId: item.id, googleHtmlLink: item.htmlLink } satisfies CalendarEvent)); const keep = current.events.filter((item) => !item.googleEventId || !items.some((google) => google.id === item.googleEventId)); return { ...current, events: [...keep, ...imported] } }) } catch (e) { setError(e instanceof Error ? e.message : 'שגיאת סנכרון') } finally { setSyncing(false) } }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const item: CalendarEvent = { id: uid('event'), title: String(data.get('title') || ''), start: new Date(String(data.get('start'))).toISOString(), end: data.get('end') ? new Date(String(data.get('end'))).toISOString() : undefined, location: String(data.get('location') || ''), notes: String(data.get('notes') || ''), projectId: String(data.get('projectId') || '') || undefined, taskId: String(data.get('taskId') || '') || undefined }; if (data.get('google') === 'on') { try { const created = await integrationsApi.createCalendarEvent({ summary: item.title, start: item.start, end: item.end, description: item.notes, location: item.location }); item.googleEventId = created.id; item.googleHtmlLink = created.htmlLink } catch (e) { setError(e instanceof Error ? e.message : 'לא ניתן ליצור ב-Google Calendar') } } setWorkspace((current) => ({ ...current, events: [...current.events, item] })); setAdding(false) }
  return <section className="card"><div className="card-head"><div><h2>יומן ופגישות</h2><p>פגישות, תאריכי יעד, מעקבים ומשימות במקום אחד.</p></div><div><button className="secondary" onClick={() => void sync()} disabled={syncing}><RefreshCw /> {syncing ? 'מסנכרן...' : 'סנכרון Google'}</button><button className="primary" onClick={() => setAdding(true)}><CalendarPlus /> אירוע</button></div></div>{error && <div className="error-banner">{error}</div>}<div className="calendar-list">{sorted.map((item) => <article key={item.id}><div className="calendar-date"><strong>{new Date(item.start).getDate()}</strong><span>{new Intl.DateTimeFormat('he-IL', { month: 'short' }).format(new Date(item.start))}</span></div><div><strong>{item.title}</strong><small>{dateTimeLabel(item.start)}{item.location ? ` · ${item.location}` : ''}</small><p>{workspace.projects.find((project) => project.id === item.projectId)?.name}</p></div>{item.googleEventId && <Chip tone="brand">Google</Chip>}{item.googleHtmlLink && <a className="icon-btn" href={item.googleHtmlLink} target="_blank" rel="noreferrer"><ExternalLink /></a>}</article>)}{!sorted.length && <EmptyState title="היומן ריק" text="צרו פגישה או תזכורת מתוך משימה או ישירות מהיומן." />}</div>{adding && <Modal title="אירוע חדש" onClose={() => setAdding(false)}><form className="form-grid" onSubmit={(e) => void submit(e)}><Field label="כותרת"><input name="title" required /></Field><Field label="התחלה"><input name="start" type="datetime-local" required /></Field><Field label="סיום"><input name="end" type="datetime-local" /></Field><Field label="מיקום"><input name="location" /></Field><Field label="פרויקט"><select name="projectId"><option value="">ללא</option>{workspace.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><Field label="משימה"><select name="taskId"><option value="">ללא</option>{workspace.tasks.map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select></Field><Field label="הערות"><textarea name="notes" rows={3} /></Field><label className="check-line"><input name="google" type="checkbox" defaultChecked /> יצירה גם ב-Google Calendar</label><div className="form-actions"><button className="primary">שמירה</button></div></form></Modal>}</section>
}

export function FilesPage({ workspace, setWorkspace, orgId, projectId }: { workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>>; orgId: string; projectId?: string }) {
  const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const records = workspace.files.filter((file) => !projectId || file.projectId === projectId)
  const add = async (file: File, chosenProjectId?: string, taskId?: string) => { setUploading(true); setError(''); try { const pid = chosenProjectId || projectId || 'general'; const result = await uploadFile(orgId, pid, file); const record: FileRecord = { id: uid('file'), projectId: pid === 'general' ? undefined : pid, taskId, name: file.name, url: result.url, storagePath: result.path, type: file.type, size: file.size, version: 1, uploadedAt: nowIso() }; setWorkspace((current) => ({ ...current, files: [record, ...current.files] })) } catch (e) { setError(e instanceof Error ? e.message : 'העלאה נכשלה') } finally { setUploading(false) } }
  return <section className="card"><div className="card-head"><div><h2>קבצים ומסמכים</h2><p>מסמכי פרויקט, תכניות, חוזים ותמונות המשויכים לפרויקט או למשימה.</p></div><label className="primary file-label"><Upload /> {uploading ? 'מעלה...' : 'העלאת קובץ'}<input type="file" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const chosen = projectId || workspace.projects[0]?.id; void add(file, chosen) }} /></label></div>{error && <div className="error-banner">{error}</div>}<div className="file-list">{records.map((file) => <a key={file.id} href={file.url} target="_blank" rel="noreferrer"><span className="file-icon"><FileText /></span><div><strong>{file.name}</strong><small>{workspace.projects.find((project) => project.id === file.projectId)?.name || 'כללי'} · גרסה {file.version} · {new Intl.NumberFormat('he-IL', { maximumFractionDigits: 1 }).format((file.size || 0) / 1024)} KB</small></div><ExternalLink /></a>)}{!records.length && <EmptyState title="אין קבצים" text="העלו מסמכים ותכניות. כאשר Supabase מחובר, הקבצים נשמרים ב-Storage המאובטח." />}</div></section>
}
