import { useEffect, useRef, useState } from 'react'
import { FolderOpen, HardDrive, RefreshCw, Settings2 } from 'lucide-react'
import { integrationsApi, type DriveSettings, type GoogleDriveFile } from '../lib/api'
import { reportAttachment, syncProjectFile } from '../lib/googleFiles'
import type { Project, Workspace } from '../types'
import { EmptyState, Modal } from './common'
import DeleteButton from './RecordDelete'

type PickerData = { action: string; docs?: { id: string; name: string }[] }
type PickerView = { setIncludeFolders(value: boolean): PickerView; setSelectFolderEnabled(value: boolean): PickerView; setMimeTypes(value: string): PickerView }
type PickerBuilder = { setOAuthToken(value: string): PickerBuilder; setDeveloperKey(value: string): PickerBuilder; setAppId(value: string): PickerBuilder; setOrigin(value: string): PickerBuilder; setLocale(value: string): PickerBuilder; addView(value: PickerView): PickerBuilder; setCallback(callback: (data: PickerData) => void): PickerBuilder; build(): { setVisible(value: boolean): void } }
declare global { interface Window { gapi?: { load(name: string, options: { callback: () => void; onerror: () => void; timeout: number; ontimeout: () => void }): void }; google?: { picker: { DocsView: new () => PickerView; PickerBuilder: new () => PickerBuilder } } } }
let pickerScript: Promise<void> | null = null
async function loadPicker() {
  if (window.google?.picker) return
  if (!pickerScript) pickerScript = new Promise<void>((resolve, reject) => {
    const load = () => window.gapi!.load('picker', { callback: resolve, onerror: () => reject(new Error('טעינת בוחר Google נכשלה')), timeout: 15000, ontimeout: () => reject(new Error('טעינת בוחר Google נכשלה')) })
    if (window.gapi) load()
    else { const script = document.createElement('script'); script.src = 'https://apis.google.com/js/api.js'; script.onload = load; script.onerror = () => reject(new Error('לא ניתן לטעון את בוחר Google')); document.head.append(script) }
  }).catch((error) => { pickerScript = null; throw error })
  await pickerScript
}
async function googleFolderPicker(onPick: (id: string) => void) {
  const config = await integrationsApi.drivePicker()
  if (!config.apiKey) throw new Error('יש להגדיר מפתח Google Picker בהגדרות המערכת. אפשר לבחור בינתיים תיקייה שכבר מורשית למערכת מהרשימה.')
  await loadPicker()
  const picker = window.google!.picker
  const view = new picker.DocsView().setIncludeFolders(true).setSelectFolderEnabled(true).setMimeTypes('application/vnd.google-apps.folder')
  new picker.PickerBuilder().setOAuthToken(config.token).setDeveloperKey(config.apiKey).setAppId(config.appId).setOrigin(window.location.origin).setLocale('he').addView(view).setCallback((result) => { if (result.action === 'picked' && result.docs?.[0]) onPick(result.docs[0].id) }).build().setVisible(true)
}
export function DriveSettingsPanel({ canEdit = true }: { canEdit?: boolean }) {
  const [settings, setSettings] = useState<DriveSettings | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false)
  useEffect(() => { let active = true; void integrationsApi.driveSettings().then((result) => { if (active) setSettings(result) }).catch((e) => { if (active) setError(e.message) }); return () => { active = false } }, [])
  const save = async () => { if (!settings) return; setBusy(true); setError(''); try { setSettings(await integrationsApi.saveDriveSettings(settings)); setSaved(true); window.dispatchEvent(new Event('rameng-drive-changed')) } catch (e) { setError(e instanceof Error ? e.message : 'שמירת הגדרות נכשלה') } finally { setBusy(false) } }
  return <section className="drive-settings"><h3>העלאה ל-Google Drive</h3><p>ההגדרות חלות על החשבון שלך. בחרו תיקייה בכל פרויקט; הקבצים והדוחות שלו יישלחו אליה.</p>{error && <div className="error-banner" role="alert">{error}</div>}{settings && <><label><input type="checkbox" disabled={!canEdit} checked={settings.autoFiles} onChange={(event) => { setSaved(false); setSettings({ ...settings, autoFiles: event.target.checked }) }} /> העלאת קבצי פרויקט אוטומטית פעם ביום</label><label><input type="checkbox" disabled={!canEdit} checked={settings.autoReports} onChange={(event) => { setSaved(false); setSettings({ ...settings, autoReports: event.target.checked }) }} /> העלאת דוחות אוטומטית פעם ביום</label><small>הדוחות נשמרים כקובצי HTML עם תמונות, לצפייה ולהדפסה / שמירה כ-PDF.</small>{canEdit && <button className="primary" disabled={busy} onClick={() => void save()}>{busy ? 'שומר...' : saved ? 'נשמר' : 'שמירת הגדרות Drive'}</button>}</>}</section>
}
export default function DriveConnection({ project, canCreateFolder, canUnlinkFolder, canShare, workspace, orgId = 'local' }: { orgId?: string; project: Project; canCreateFolder: boolean; canUnlinkFolder: boolean; canShare: boolean; workspace?: Workspace }) {
  const [fileSearch, setFileSearch] = useState('')
  const [sharing, setSharing] = useState<{ id: string; name: string } | null>(null)
  const [shareEmail, setShareEmail] = useState('')
  const [shareRole, setShareRole] = useState('reader')
  const [permissions, setPermissions] = useState<{ id: string; emailAddress?: string; role: string; canRevoke: boolean }[]>([])
  const [categoryId, setCategoryId] = useState('')
  const loadSharing = async (file: { id: string; name: string }) => { setSharing(file); setPermissions([]); await run(async () => { const result = await integrationsApi.driveSharing(orgId, project.id, file.id); setPermissions(result.permissions) }) }
  const [folder, setFolder] = useState<{ id: string; name?: string; readOnly?: boolean; protected?: boolean; webViewLink: string } | null>(null); const [files, setFiles] = useState<GoogleDriveFile[]>([])
  const [folders, setFolders] = useState<GoogleDriveFile[]>([]); const [query, setQuery] = useState(''); const [nextPageToken, setNextPageToken] = useState('')
  const [allowUploads, setAllowUploads] = useState(false); const [choosing, setChoosing] = useState(false); const [settings, setSettings] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [path, setPath] = useState<{ id: string; name: string }[]>([]); const [filePage, setFilePage] = useState(''); const [completeAccess, setCompleteAccess] = useState(true); const readVersion = useRef(0)
  const browse = async (id: string, more = false, force = false) => { const version = ++readVersion.current; const result = await integrationsApi.driveFiles(id, more ? filePage : '', force); if (version !== readVersion.current) return; setFiles((current) => more ? [...current, ...result.files.filter((item) => !current.some((file) => file.id === item.id))] : result.files); setFilePage(result.nextPageToken); setCompleteAccess(result.completeAccess) }
  const refresh = async (id = path.at(-1)?.id || folder?.id) => { if (id) await browse(id, false, true) }
  useEffect(() => { let active = true; setFolder(null); setFiles([]); void integrationsApi.projectDriveFolder(project.id).then(async (result) => { if (!active) return; setFolder(result.folder); if (result.folder) { setPath([{ id: result.folder.id, name: result.folder.name || 'תיקיית הפרויקט' }]); const list = await integrationsApi.driveFiles(result.folder.id); if (active) { setFiles(list.files); setFilePage(list.nextPageToken); setCompleteAccess(list.completeAccess) } } }).catch((e) => { if (active) setError(e.message) }); return () => { active = false } }, [project.id])
  useEffect(() => { const refresh = () => { const id = path.at(-1)?.id || folder?.id; if (id) void browse(id).catch((e) => setError(e.message)) }; window.addEventListener('rameng-google-synced', refresh); return () => window.removeEventListener('rameng-google-synced', refresh) }, [folder?.id, path])
  const connect = async (id?: string) => { setBusy(true); setError(''); try { const result = await integrationsApi.ensureProjectFolder({ projectId: project.id, name: `${project.name} - ${project.address || 'פרויקט'}`, folderId: id, readOnly: !!id }); setFolder(result); setPath([{ id: result.id, name: result.name || 'תיקיית הפרויקט' }]); setChoosing(false); await refresh(result.id); setMessage(result.readOnly ? 'התיקייה מחוברת לצפייה בלבד. קבצים קיימים לא ישתנו.' : 'התיקייה מחוברת. קבצי ודוחות הפרויקט יסונכרנו אליה.'); window.dispatchEvent(new Event('rameng-drive-changed')) } catch (e) { setError(e instanceof Error ? e.message : 'חיבור Drive נכשל') } finally { setBusy(false) } }
  const listFolders = async (more = false) => { setBusy(true); setError(''); try { const result = await integrationsApi.driveFolders(query, more ? nextPageToken : ''); setFolders((current) => more ? [...current, ...result.folders] : result.folders); setNextPageToken(result.nextPageToken) } catch (e) { setError(e instanceof Error ? e.message : 'טעינת תיקיות נכשלה') } finally { setBusy(false) } }
  const run = async (action: () => Promise<unknown>) => { setBusy(true); setError(''); try { await action() } catch (e) { setError(e instanceof Error ? e.message : 'פעולת Drive נכשלה') } finally { setBusy(false) } }
  const syncAll = async () => { if (!workspace) return; setMessage(''); await run(async () => { for (const file of workspace.files.filter((file) => file.projectId === project.id)) await syncProjectFile(file, undefined, false); for (const report of workspace.reports.filter((report) => report.projectId === project.id)) await integrationsApi.uploadDrive({ projectId: project.id, recordId: report.id, kind: 'report', automatic: false, file: await reportAttachment(report, workspace) }); await refresh(); setMessage('סנכרון הפרויקט הסתיים בהתאם להגדרות ההעלאה.') }) }
  return <section className="card project-module-card project-drive-card"><div className="card-head"><h2>Google Drive</h2><div className="drive-toolbar">{canCreateFolder && <><button className="primary" disabled={busy} onClick={() => { setChoosing(true); void listFolders() }}><FolderOpen /> בחירת תיקייה קיימת</button><button className="secondary" disabled={busy || !!folder} onClick={() => void connect()}><HardDrive /> יצירת תיקייה חדשה</button><button className="secondary" onClick={() => { setAllowUploads(!!folder && !folder.readOnly); setSettings(true) }}><Settings2 /> הגדרות Drive</button></>}{folder && <><a className="secondary link-button" href={folder.webViewLink} target="_blank" rel="noreferrer">פתיחת התיקייה</a><button className="secondary" disabled={busy} onClick={() => void run(() => refresh())}><RefreshCw /> רענון</button>{canCreateFolder && workspace && !folder.readOnly && <button className="secondary" disabled={busy} onClick={() => void syncAll()}>סנכרון קבצים ודוחות</button>}{canUnlinkFolder && <DeleteButton label="ביטול קישור תיקייה" message="לבטל את קישור התיקייה לחשבון שלך? הקבצים המקוריים ב-Drive יישמרו." onConfirm={() => { void run(async () => { await integrationsApi.unlinkProjectDriveFolder(project.id); setFolder(null); setFiles([]); window.dispatchEvent(new Event('rameng-drive-changed')) }) }} />}</>}</div></div>
    {error && !choosing && <div className="error-banner" role="alert">{error}</div>}{message && <div className="success-banner" role="status">{message}</div>}

    {folder && <><p className="info-banner">{folder.readOnly ? 'צפייה בלבד — המערכת אינה מעלה, משנה או מוחקת קבצים בתיקייה זו.' : 'העלאת קבצי הפרויקט והדוחות מותרת בתיקייה זו.'}</p>
      {!completeAccess && <div className="info-banner"><p>כדי להציג את כל הקבצים והתיקיות הקיימים, נדרשת הרשאת קריאה לשמות ולקישורים ב-Drive. היא אינה מאפשרת שינוי או מחיקה.</p><button className="primary" disabled={busy} onClick={() => void run(async () => { const result = await integrationsApi.googleAuthUrl(true); window.location.assign(result.url) })}>חיבור לצפייה בכל קבצי Drive</button></div>}
      <nav className="drive-breadcrumbs" aria-label="נתיב תיקייה">{path.map((item, index) => <button key={item.id} className="secondary" disabled={busy} onClick={() => { setPath(path.slice(0, index + 1)); void run(() => browse(item.id)) }}>{item.name}</button>)}</nav></>}
    {folder && <div className="toolbar"><input aria-label="חיפוש קבצי Drive" value={fileSearch} onChange={event => setFileSearch(event.target.value)} placeholder="חיפוש בתיקייה הנוכחית" />{canCreateFolder && !folder.readOnly && workspace && <><select aria-label="בחירת מקצוע לתיקיית Drive" value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">מקצוע לתיקייה</option>{workspace.categories.filter(category => project.categoryIds?.includes(category.id)).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><button type="button" className="secondary" disabled={busy || !categoryId} onClick={() => void run(async () => { const category = workspace.categories.find(item => item.id === categoryId)!; const result = await integrationsApi.driveCategory({ orgId, projectId: project.id, folderId: folder.id, categoryId, name: category.name }); setPath([{ id: folder.id, name: folder.name || 'תיקיית הפרויקט' }, result]); await browse(result.id, false, true) })}>פתיחה / יצירת תיקיית מקצוע</button></>}{canShare && <button type="button" className="secondary" disabled={busy || !!folder?.readOnly} onClick={() => void loadSharing(path.at(-1) || { id: folder.id, name: folder.name || 'תיקיית הפרויקט' })}>שיתוף התיקייה הנוכחית</button>}</div>}
    <div className="drive-list">{files.filter(file => file.name.toLowerCase().includes(fileSearch.toLowerCase())).map((file) => file.mimeType === 'application/vnd.google-apps.folder' ? <button type="button" key={file.id} className="drive-folder-row" disabled={busy} onClick={() => { setPath([...path, { id: file.id, name: file.name }]); void run(() => browse(file.id)) }}><FolderOpen /><strong>{file.name}</strong><small>פתיחת תיקייה</small></button> : <div key={file.id}><a href={file.webViewLink || `https://drive.google.com/file/d/${file.id}/view`} target="_blank" rel="noreferrer"><strong>{file.name}</strong><small>{file.mimeType} · {file.modifiedTime || ''} · {file.size ? `${Math.round(Number(file.size) / 1024)} KB` : ''}</small></a>{canShare && <button type="button" className="secondary" disabled={busy || !!folder?.readOnly} onClick={() => void loadSharing(file)}>שיתוף קובץ</button>}</div>)}{!folder && <EmptyState title="Drive עדיין לא מחובר" text="בחרו תיקייה קיימת או צרו תיקייה חדשה באמצעות הכפתורים למעלה." />}{folder && !files.length && <div className="table-empty">{completeAccess ? 'אין קבצים בתיקייה.' : 'אין קבצים מורשים להצגה. חברו את הרשאת הצפייה כדי לראות את התוכן הקיים.'}</div>}</div>
    {filePage && <button className="secondary" disabled={busy} onClick={() => void run(() => browse(path.at(-1)?.id || folder!.id, true))}>קבצים נוספים</button>}
    {sharing && <Modal title={`שיתוף — ${sharing.name}`} onClose={() => setSharing(null)}><p>שיתוף תיקייה חל על התוכן שלה ועל תיקיות המשנה. Google ישלח הודעה לנמען. רק הרשאות שנוספו כאן ניתנות לביטול כאן.</p>{error && <p role="alert">{error}</p>}<label>נמען<input type="email" dir="ltr" aria-label="מייל לשיתוף Drive" list="drive-collaborators" value={shareEmail} onChange={event => setShareEmail(event.target.value)} /></label><datalist id="drive-collaborators">{workspace?.team.filter(member => member.active).map(member => <option key={member.id} value={member.email}>{member.name}</option>)}{workspace?.contacts.filter(contact => contact.email).map(contact => <option key={contact.id} value={contact.email}>{contact.name}</option>)}</datalist><select aria-label="הרשאת שיתוף Drive" value={shareRole} onChange={event => setShareRole(event.target.value)}><option value="reader">צפייה</option><option value="commenter">תגובות</option></select><button className="primary" type="button" disabled={busy || !shareEmail || !!folder?.readOnly} onClick={() => void run(async () => { await integrationsApi.shareDrive({ orgId, projectId: project.id, fileId: sharing.id, email: shareEmail, role: shareRole }); const result = await integrationsApi.driveSharing(orgId, project.id, sharing.id); setPermissions(result.permissions); setMessage('הקובץ / התיקייה שותפו דרך Google Drive') })}>שיתוף ושליחת הודעה</button>{permissions.map(permission => <article key={permission.id}><span>{permission.emailAddress || 'הרשאה ללא כתובת מייל'} · {permission.role}</span>{permission.canRevoke && <button className="secondary" type="button" disabled={busy || !!folder?.readOnly} onClick={() => void run(async () => { await integrationsApi.revokeDriveShare({ orgId, projectId: project.id, fileId: sharing.id, permissionId: permission.id }); setPermissions(current => current.filter(item => item.id !== permission.id)) })}>ביטול גישה</button>}</article>)}</Modal>}
    {choosing && <Modal title="בחירת תיקיית Google Drive" onClose={() => setChoosing(false)}><p>לבחירה מכל התיקיות בחשבון שלכם, פתחו את בוחר Google. הבחירה מעניקה למערכת גישה לתיקייה שנבחרה.</p><button className="primary" disabled={busy} onClick={() => void run(() => googleFolderPicker((id) => { void connect(id) }))}><FolderOpen /> בחירה מתוך Google Drive</button>{error && <div className="error-banner" role="alert">{error}</div>}<form className="inline-create" onSubmit={(event) => { event.preventDefault(); void listFolders() }}><label>תיקיות שכבר מחוברות למערכת<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="חיפוש שם תיקייה" /></label><button className="secondary" disabled={busy}>חיפוש</button></form><div className="drive-folder-choices">{folders.map((item) => <button className="secondary" disabled={busy} key={item.id} onClick={() => void connect(item.id)}><FolderOpen /> {item.name}</button>)}{!folders.length && <p>לגישה לתיקייה קיימת שטרם נבחרה, השתמשו בבוחר Google למעלה.</p>}{nextPageToken && <button disabled={busy} onClick={() => void listFolders(true)}>תיקיות נוספות</button>}</div></Modal>}
    {settings && <Modal title="הגדרות Drive" onClose={() => setSettings(false)}><DriveSettingsPanel />{folder && <section className="drive-settings"><h3>תיקיית הפרויקט</h3>{folder.protected ? <p>התיקייה הוגדרה לצפייה בלבד לפי בקשתכם. העלאה ושינוי חסומים.</p> : <><label><input type="checkbox" checked={allowUploads} disabled={busy} onChange={(e) => setAllowUploads(e.target.checked)} /> אפשר העלאת קבצי פרויקט ודוחות לתיקייה זו</label><button className="primary" disabled={busy} onClick={() => void run(async () => { const result = await integrationsApi.ensureProjectFolder({ projectId: project.id, name: project.name, folderId: folder.id, readOnly: !allowUploads }); setFolder(result); setSettings(false); window.dispatchEvent(new Event('rameng-drive-changed')) })}>שמירת הרשאת העלאה לפרויקט</button></>}</section>}</Modal>}
  </section>
}
