import { useContext, useState } from 'react'
import type { MeetingSummary, Workspace } from '../types'
import { Modal, nowIso, uid } from './common'
import { WorkspaceSaveContext } from './WorkspaceSave'

export const escapeMeetingHtml = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!))

export function meetingHtml(summary: MeetingSummary, workspace: Workspace) {
  const e = escapeMeetingHtml; const project = workspace.projects.find(item => item.id === summary.projectId)
  const rows = summary.taskIds.map(id => { const task = workspace.tasks.find(item => item.id === id && item.projectId === summary.projectId); return task ? `<tr><td>${e(task.title)}${task.description ? `<p>${e(task.description)}</p>` : ''}</td><td>${e(workspace.categories.filter(category => task.categoryIds?.includes(category.id)).map(item => item.name).join(', '))}</td><td>${e(workspace.team.find(item => item.id === task.assigneeId)?.name || 'לא משויך')}</td><td>${e(task.status || '')}</td><td>${e(task.dueDate || '')}</td><td>${e(summary.taskNotes[id] || '')}</td></tr>` : `<tr><td colspan="6">משימה שהוסרה: ${e(id)}</td></tr>` }).join('')
  return `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><title>${e(summary.title)}</title><style>body{font:14px Arial,sans-serif;direction:rtl;text-align:right;padding:24px;color:#182b25}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #bbb;padding:8px;vertical-align:top;text-align:right;white-space:pre-wrap;overflow-wrap:anywhere}thead{display:table-header-group}tr{break-inside:avoid}.notes{white-space:pre-wrap}@page{size:A4 landscape;margin:15mm}@media print{button{display:none}}</style></head><body><button onclick="window.print()">הדפסה / שמירה כ-PDF</button><h1>${e(summary.title)}</h1><p>${e(project?.name || '')} · ${e(summary.date)}</p><p class="notes">${e(summary.notes)}</p><table><thead><tr><th>משימה</th><th>מקצוע</th><th>אחראי</th><th>סטטוס</th><th>יעד</th><th>הערות לפגישה</th></tr></thead><tbody>${rows}</tbody></table></body></html>`
}

export default function MeetingSummaries({ workspace, setWorkspace, projectId, selectedTaskIds, canEdit, canDelete }: { workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>>; projectId: string; selectedTaskIds: string[]; canEdit: boolean; canDelete: boolean }) {
  const { state: saveState, dirty, refresh: refreshWorkspace } = useContext(WorkspaceSaveContext)
  const [editingId, setEditingId] = useState(''); const [error, setError] = useState('')
  const summary = workspace.meetingSummaries.find(item => item.id === editingId && item.projectId === projectId)
  const patch = (value: Partial<MeetingSummary>) => setWorkspace(current => ({ ...current, meetingSummaries: current.meetingSummaries.map(item => item.id === editingId ? { ...item, ...value, updatedAt: nowIso() } : item) }))
  const addTasks = (id: string) => setWorkspace(current => ({ ...current, meetingSummaries: current.meetingSummaries.map(item => item.id === id ? { ...item, taskIds: [...new Set([...item.taskIds, ...selectedTaskIds.filter(taskId => current.tasks.some(task => task.id === taskId && task.projectId === projectId))])], updatedAt: nowIso() } : item) }))
  const exportPdf = () => { if (!summary) return; const tab = window.open('', '_blank'); if (!tab) { setError('הדפדפן חסם את חלון ההדפסה. אפשרו חלונות קופצים.'); return } tab.document.open(); tab.document.write(meetingHtml(summary, workspace)); tab.document.close(); tab.focus(); tab.print() }
  const refresh = async () => { if (dirty || ['saving','error','conflict'].includes(saveState)) { setError('יש לשמור את סביבת העבודה לפני רענון פרטי המשימות.'); return } try { await refreshWorkspace(); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'רענון המשימות נכשל') } }
  return <section className="meeting-summaries"><div className="toolbar"><strong>סיכומי פגישה · {selectedTaskIds.length} משימות נבחרו</strong>{canEdit && <button className="secondary" type="button" onClick={() => { const id = uid('meeting'); setWorkspace(current => ({ ...current, meetingSummaries: [...current.meetingSummaries, { id, projectId, title: 'סיכום פגישת פרויקט', date: new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jerusalem', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()), taskIds: selectedTaskIds, notes: workspace.projects.find(item => item.id === projectId)?.meetingTemplate || '', taskNotes: {}, updatedAt: nowIso() }] })); setEditingId(id) }}>הוסף לסיכום פגישה חדש</button>}</div>
    {workspace.meetingSummaries.filter(item => item.projectId === projectId).map(item => <div key={item.id} className="inline-create"><button className="secondary" type="button" onClick={() => setEditingId(item.id)}>{item.title} · {item.date} ({item.taskIds.length})</button>{canEdit && selectedTaskIds.length > 0 && <button type="button" className="secondary" onClick={() => { addTasks(item.id); setEditingId(item.id) }}>הוספת הנבחרות לסיכום</button>}</div>)}
    {summary && <Modal title="סיכום פגישה" wide onClose={() => setEditingId('')}><p>פרטי המשימות מוצגים מנתוני המערכת ומתעדכנים עם המשימות. הערות הפגישה נשמרות בנפרד.</p>{error && <p role="alert">{error}</p>}<label>כותרת<input disabled={!canEdit} value={summary.title} onChange={event => patch({ title: event.target.value })} /></label><label>תאריך<input disabled={!canEdit} type="date" value={summary.date} onChange={event => patch({ date: event.target.value })} /></label><label>הערות וסעיפים ידניים<textarea disabled={!canEdit} value={summary.notes} onChange={event => patch({ notes: event.target.value })} /></label>{summary.taskIds.map(id => { const task = workspace.tasks.find(item => item.id === id && item.projectId === projectId); return <article className="meeting-task" key={id}><strong>{task?.title || 'משימה שהוסרה'}</strong><p>{task?.status} · {workspace.team.find(item => item.id === task?.assigneeId)?.name || 'ללא אחראי'} · {task?.dueDate}</p><textarea aria-label={`הערות לפגישה עבור ${task?.title || id}`} disabled={!canEdit} value={summary.taskNotes[id] || ''} onChange={event => patch({ taskNotes: { ...summary.taskNotes, [id]: event.target.value } })} />{canEdit && <button type="button" className="secondary" onClick={() => patch({ taskIds: summary.taskIds.filter(taskId => taskId !== id) })}>הסרה מהסיכום</button>}</article> })}<div className="form-actions"><button type="button" className="secondary" onClick={() => void refresh()}>רענון פרטי משימות</button><button type="button" className="primary" onClick={exportPdf}>ייצוא PDF</button>{canDelete && <button type="button" className="secondary" onClick={() => { setWorkspace(current => ({ ...current, meetingSummaries: current.meetingSummaries.filter(item => item.id !== summary.id) })); setEditingId('') }}>מחיקת סיכום</button>}</div><p>הסיכום נשמר עם סביבת העבודה. בחלון ההדפסה בחרו ״שמירה כ-PDF״.</p></Modal>}
  </section>
}
