import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ArrowRight, CalendarDays, ExternalLink, FileText, FolderKanban, HardDrive, Mail, Plus, RefreshCw, Send, Settings2 } from 'lucide-react'
import { integrationsApi, type GmailApiMessage, type GoogleDriveFile } from '../lib/api'
import type { Project, ProjectStatus, Task, Workspace } from '../types'
import { Chip, EmptyState, Field, Modal, dateLabel, dateTimeLabel, nowIso, uid } from './common'
import TaskBoard from './TaskBoard'
import ReportsPage from './Reports'
import { FilesPage } from './CalendarFiles'

export function ProjectsPage({ workspace, setWorkspace, onOpen }: { workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>>; onOpen: (id: string) => void }) {
  const [adding, setAdding] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const project: Project = { id: uid('project'), name: String(data.get('name') || ''), address: String(data.get('address') || ''), clientIds: data.getAll('clientIds').map(String), managerId: String(data.get('managerId') || '') || undefined, status: String(data.get('status') || 'בתכנון') as ProjectStatus, startDate: String(data.get('startDate') || '') || undefined, targetDate: String(data.get('targetDate') || '') || undefined, progress: 0, notes: String(data.get('notes') || ''), createdAt: nowIso() }; setWorkspace((current) => ({ ...current, projects: [...current.projects, project] })); setAdding(false); onOpen(project.id) }
  return <><div className="page-action-row"><button className="primary" onClick={() => setAdding(true)}><Plus /> פרויקט חדש</button></div><div className="project-card-grid">{workspace.projects.map((project) => { const open = workspace.tasks.filter((task) => task.projectId === project.id && !['בוצע', 'סגור'].includes(task.status)).length; const reports = workspace.reports.filter((report) => report.projectId === project.id).length; return <button className="project-card card" key={project.id} onClick={() => onOpen(project.id)}><div className="project-card-top"><span><FolderKanban /></span><Chip tone={project.status === 'בביצוע' ? 'good' : project.status === 'מוקפא' ? 'bad' : 'brand'}>{project.status}</Chip></div><h2>{project.name}</h2><p>{project.address || 'ללא כתובת'}</p><div className="progress"><i style={{ width: `${project.progress}%` }} /></div><div className="project-card-stats"><span><b>{project.progress}%</b> התקדמות</span><span><b>{open}</b> משימות פתוחות</span><span><b>{reports}</b> דוחות</span></div></button>})}{!workspace.projects.length && <div className="card project-empty"><EmptyState title="אין פרויקטים" text="כל פרויקט מרכז משימות, מיילים, פגישות, דוחות, תמונות ומסמכים." action={<button className="primary" onClick={() => setAdding(true)}><Plus /> יצירת פרויקט ראשון</button>} /></div>}</div>{adding && <Modal title="פרויקט חדש" onClose={() => setAdding(false)} wide><form className="form-grid two-col" onSubmit={submit}><Field label="שם הפרויקט"><input name="name" required /></Field><Field label="כתובת"><input name="address" /></Field><Field label="סטטוס"><select name="status"><option>בתכנון</option><option>בביצוע</option><option>בהמתנה</option><option>הושלם</option><option>מוקפא</option></select></Field><Field label="מנהל פרויקט"><select name="managerId"><option value="">לא משויך</option>{workspace.team.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></Field><Field label="תאריך התחלה"><input name="startDate" type="date" /></Field><Field label="יעד"><input name="targetDate" type="date" /></Field><Field label="לקוחות"><select name="clientIds" multiple size={4}>{workspace.contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></Field><Field label="הערות"><textarea name="notes" rows={4} /></Field><div className="form-actions full"><button className="primary">יצירת פרויקט</button></div></form></Modal>}</>
}

type ProjectTab = 'summary' | 'tasks' | 'mail' | 'calendar' | 'drive' | 'reports' | 'files'
export function ProjectWorkspace({ projectId, workspace, setWorkspace, orgId, onBack }: { projectId: string; workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>>; orgId: string; onBack: () => void }) {
  const project = workspace.projects.find((item) => item.id === projectId)
  const [tab, setTab] = useState<ProjectTab>('summary')
  const [emailTask, setEmailTask] = useState<Task | null>(null)
  if (!project) return <EmptyState title="הפרויקט לא נמצא" text="ייתכן שהפרויקט נמחק או שהמידע השתנה." action={<button className="secondary" onClick={onBack}>חזרה</button>} />
  const tasks = workspace.tasks.filter((task) => task.projectId === project.id); const events = workspace.events.filter((event) => event.projectId === project.id); const files = workspace.files.filter((file) => file.projectId === project.id); const reports = workspace.reports.filter((report) => report.projectId === project.id)
  const open = tasks.filter((task) => !['בוצע', 'סגור'].includes(task.status)); const overdue = open.filter((task) => task.followUpDate && new Date(task.followUpDate).getTime() < Date.now()); const openReportItems = reports.flatMap((report) => report.sections.flatMap((section) => section.items)).filter((item) => !['תקין', 'בוצע', 'סגור'].includes(item.status))
  const patchProject = (patch: Partial<Project>) => setWorkspace((current) => ({ ...current, projects: current.projects.map((item) => item.id === project.id ? { ...item, ...patch } : item) }))
  const tabs: [ProjectTab, string][] = [['summary', 'תמונת מצב'], ['tasks', 'משימות'], ['mail', 'מייל'], ['calendar', 'יומן'], ['drive', 'Google Drive'], ['reports', 'דוחות פיקוח'], ['files', 'קבצים']]
  return <div className="project-workspace"><div className="project-header card"><button className="back-button" onClick={onBack}><ArrowRight /> כל הפרויקטים</button><div className="project-title"><div><span className="eyebrow">פרויקט</span><h1>{project.name}</h1><p>{project.address || 'ללא כתובת'} · מנהל: {workspace.team.find((member) => member.id === project.managerId)?.name || 'לא משויך'}</p></div><div className="project-edit-inline"><select value={project.status} onChange={(e) => patchProject({ status: e.target.value as ProjectStatus })}><option>בתכנון</option><option>בביצוע</option><option>בהמתנה</option><option>הושלם</option><option>מוקפא</option></select><label>התקדמות <input type="number" min="0" max="100" value={project.progress} onChange={(e) => patchProject({ progress: Math.max(0, Math.min(100, Number(e.target.value))) })} />%</label></div></div><nav className="project-tabs">{tabs.map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav></div>
    {tab === 'summary' && <div className="project-summary"><div className="metric-grid"><article className="metric card"><div><small>משימות פתוחות</small><strong>{open.length}</strong><p>{overdue.length} באיחור / דורשות מעקב</p></div></article><article className="metric card"><div><small>סעיפי פיקוח פתוחים</small><strong>{openReportItems.length}</strong><p>{reports.length} דוחות בפרויקט</p></div></article><article className="metric card"><div><small>פגישות ואירועים</small><strong>{events.length}</strong><p>{events.filter((event) => new Date(event.start).getTime() > Date.now()).length} עתידיים</p></div></article><article className="metric card"><div><small>מסמכים</small><strong>{files.length}</strong><p>{project.driveFolderId ? 'Drive מחובר' : 'Drive טרם חובר'}</p></div></article></div><section className="card"><div className="card-head"><div><h2>מה פתוח עכשיו</h2><p>מי אחראי, מתי התחיל, מתי צריך מעקב ומה דורש טיפול.</p></div></div><div className="summary-open-list">{open.slice(0, 12).map((task) => <button key={task.id} onClick={() => setTab('tasks')}><div><strong>{task.title}</strong><small>{workspace.team.find((member) => member.id === task.assigneeId)?.name || 'ללא אחראי'} · התחלה {dateLabel(task.startDate)}</small></div><Chip tone={task.status === 'דורש מעקב' ? 'bad' : 'brand'}>{task.status}</Chip><span>{dateLabel(task.followUpDate || task.dueDate)}</span></button>)}{!open.length && <EmptyState title="אין משימות פתוחות" text="הפרויקט מעודכן ואין כרגע משימות פתוחות." />}</div></section></div>}
    {tab === 'tasks' && <section className="card board-card"><TaskBoard workspace={workspace} setWorkspace={setWorkspace} projectId={project.id} onEmail={(task) => { setEmailTask(task); setTab('mail') }} /></section>}
    {tab === 'mail' && <ProjectMail project={project} workspace={workspace} setWorkspace={setWorkspace} initialTask={emailTask} />}
    {tab === 'calendar' && <ProjectCalendar project={project} workspace={workspace} setWorkspace={setWorkspace} />}
    {tab === 'drive' && <ProjectDrive project={project} workspace={workspace} setWorkspace={setWorkspace} />}
    {tab === 'reports' && <ReportsPage workspace={workspace} setWorkspace={setWorkspace} orgId={orgId} projectId={project.id} />}
    {tab === 'files' && <FilesPage workspace={workspace} setWorkspace={setWorkspace} orgId={orgId} projectId={project.id} />}
  </div>
}

function ProjectMail({ project, workspace, setWorkspace, initialTask }: { project: Project; workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>>; initialTask: Task | null }) {
  const eligible = workspace.tasks.filter((task) => task.projectId === project.id); const [selectedId, setSelectedId] = useState(initialTask?.id || eligible[0]?.id || ''); const selected = workspace.tasks.find((task) => task.id === selectedId); const [messages, setMessages] = useState<GmailApiMessage[]>([]); const [loading, setLoading] = useState(false); const [searching, setSearching] = useState(false); const [searchResults, setSearchResults] = useState<{ id: string; snippet: string; subject?: string; from?: string }[]>([]); const [error, setError] = useState('')
  const updateTask = (id: string, patch: Partial<Task>) => setWorkspace((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, ...patch } : task) }))
  const load = async (threadId: string) => { setLoading(true); setError(''); try { const result = await integrationsApi.gmailThread(threadId); setMessages(result.messages) } catch (e) { setError(e instanceof Error ? e.message : 'לא ניתן לטעון את ההתכתבות') } finally { setLoading(false) } }
  useEffect(() => { if (selected?.gmailThreadId) void load(selected.gmailThreadId); else setMessages([]) }, [selectedId, selected?.gmailThreadId])
  const send = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); const to = String(data.get('to') || selected.emailTo || ''); const subject = String(data.get('subject') || selected.title); const body = String(data.get('body') || ''); setLoading(true); setError(''); try { const result = await integrationsApi.sendMail({ to, subject, body, threadId: selected.gmailThreadId }); updateTask(selected.id, { emailTo: to, gmailThreadId: result.threadId }); event.currentTarget.reset(); await load(result.threadId) } catch (e) { setError(e instanceof Error ? e.message : 'שליחת המייל נכשלה') } finally { setLoading(false) } }
  const search = async () => { setSearching(true); setError(''); try { const clientEmails = project.clientIds.map((id) => workspace.contacts.find((contact) => contact.id === id)?.email).filter(Boolean); const query = [`"${project.name}"`, ...clientEmails.map((email) => `from:${email} OR to:${email}`)].filter(Boolean).join(' OR '); const result = await integrationsApi.gmailSearch(query); setSearchResults(result.threads) } catch (e) { setError(e instanceof Error ? e.message : 'חיפוש Gmail נכשל') } finally { setSearching(false) } }
  return <section className="mail-workspace card"><aside><div className="mail-aside-head"><strong>התכתבויות לפי משימה</strong><button className="icon-btn" onClick={() => void search()} title="איתור מיילים בפרויקט"><RefreshCw /></button></div>{eligible.map((task) => <button key={task.id} className={task.id === selectedId ? 'active' : ''} onClick={() => setSelectedId(task.id)}><Mail /><span><strong>{task.title}</strong><small>{task.gmailThreadId ? 'התכתבות מחוברת' : task.emailTo || 'טרם נשלח מייל'}</small></span></button>)}{!eligible.length && <div className="table-empty">אין משימות בפרויקט.</div>}</aside><main>{error && <div className="error-banner">{error}</div>}{selected ? <><div className="mail-main-head"><div><h2>{selected.title}</h2><p>כל מייל שנשלח מהמשימה נשמר באותו Gmail thread, ולכן התשובות חוזרות אוטומטית לאותה משימה.</p></div>{selected.gmailThreadId && <Chip tone="good">Thread מחובר</Chip>}</div>{searchResults.length > 0 && <div className="mail-search-results"><strong>מיילים רלוונטיים שנמצאו</strong>{searchResults.slice(0, 8).map((thread) => <button key={thread.id} onClick={() => { updateTask(selected.id, { gmailThreadId: thread.id }); setSearchResults([]) }}><div><b>{thread.subject || 'ללא נושא'}</b><small>{thread.from}</small><p>{thread.snippet}</p></div><span>שיוך למשימה</span></button>)}</div>}<div className="thread-list">{loading && !messages.length ? <div className="table-empty">טוען התכתבות...</div> : messages.map((message) => <article key={message.id}><header><strong>{message.from}</strong><span>{dateTimeLabel(message.date)}</span></header><h3>{message.subject}</h3><p>{message.body || message.snippet}</p></article>)}{!messages.length && selected.gmailThreadId && !loading && <div className="table-empty">לא נמצאו הודעות ב-thread.</div>}</div><form className="mail-compose" onSubmit={(e) => void send(e)}><input name="to" type="email" required defaultValue={selected.emailTo || ''} placeholder="אל" /><input name="subject" required defaultValue={selected.title} placeholder="נושא" /><textarea name="body" rows={6} required placeholder="כתיבת הודעה..." /><button className="primary" disabled={loading}><Send /> {loading ? 'שולח...' : selected.gmailThreadId ? 'שליחה באותה התכתבות' : 'שליחת מייל'}</button></form></> : <EmptyState title="בחרו משימה" text="המיילים בפרויקט משויכים למשימות כדי שכל התכתבות תישאר בהקשר הנכון." />}</main></section>
}

function ProjectCalendar({ project, workspace, setWorkspace }: { project: Project; workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>> }) {
  const events = workspace.events.filter((event) => event.projectId === project.id).sort((a, b) => a.start.localeCompare(b.start)); const [addingTask, setAddingTask] = useState(''); const [error, setError] = useState('')
  const createFromTask = async () => { const task = workspace.tasks.find((item) => item.id === addingTask); if (!task) return; const start = task.followUpDate ? new Date(`${task.followUpDate}T09:00:00`).toISOString() : new Date(Date.now() + 86400000).toISOString(); try { const google = await integrationsApi.createCalendarEvent({ summary: `${project.name}: ${task.title}`, start, description: task.description }); setWorkspace((current) => ({ ...current, events: [...current.events, { id: uid('event'), projectId: project.id, taskId: task.id, title: task.title, start, notes: task.description, googleEventId: google.id, googleHtmlLink: google.htmlLink }] })); setAddingTask('') } catch (e) { setError(e instanceof Error ? e.message : 'יצירת אירוע נכשלה') } }
  return <section className="card"><div className="card-head"><div><h2>יומן הפרויקט</h2><p>פגישות, יעדים ומועדי מעקב.</p></div><div className="inline-create"><select value={addingTask} onChange={(e) => setAddingTask(e.target.value)}><option value="">יצירת תזכורת ממשימה...</option>{workspace.tasks.filter((task) => task.projectId === project.id).map((task) => <option key={task.id} value={task.id}>{task.title}</option>)}</select><button className="secondary" disabled={!addingTask} onClick={() => void createFromTask()}><CalendarDays /> יצירה ביומן</button></div></div>{error && <div className="error-banner">{error}</div>}<div className="calendar-list">{events.map((event) => <article key={event.id}><div className="calendar-date"><strong>{new Date(event.start).getDate()}</strong><span>{new Intl.DateTimeFormat('he-IL', { month: 'short' }).format(new Date(event.start))}</span></div><div><strong>{event.title}</strong><small>{dateTimeLabel(event.start)}{event.location ? ` · ${event.location}` : ''}</small></div>{event.googleHtmlLink && <a className="icon-btn" href={event.googleHtmlLink} target="_blank" rel="noreferrer"><ExternalLink /></a>}</article>)}{!events.length && <EmptyState title="אין אירועים בפרויקט" text="ניתן ליצור פגישה או תזכורת ישירות ממשימה." />}</div></section>
}

function ProjectDrive({ project, workspace, setWorkspace }: { project: Project; workspace: Workspace; setWorkspace: React.Dispatch<React.SetStateAction<Workspace>> }) {
  const [files, setFiles] = useState<GoogleDriveFile[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const patchProject = (patch: Partial<Project>) => setWorkspace((current) => ({ ...current, projects: current.projects.map((item) => item.id === project.id ? { ...item, ...patch } : item) }))
  const connect = async () => { setLoading(true); setError(''); try { const folder = await integrationsApi.ensureProjectFolder({ projectId: project.id, name: `${project.name} - ${project.address || 'פרויקט'}`, parentId: workspace.settings.driveRootFolderId || undefined }); patchProject({ driveFolderId: folder.id, driveFolderUrl: folder.webViewLink }); const list = await integrationsApi.driveFiles(folder.id); setFiles(list.files) } catch (e) { setError(e instanceof Error ? e.message : 'חיבור Drive נכשל') } finally { setLoading(false) } }
  const refresh = async () => { if (!project.driveFolderId) return connect(); setLoading(true); try { const list = await integrationsApi.driveFiles(project.driveFolderId); setFiles(list.files) } catch (e) { setError(e instanceof Error ? e.message : 'טעינת קבצים נכשלה') } finally { setLoading(false) } }
  return <section className="card"><div className="card-head"><div><h2>Google Drive</h2><p>לכל פרויקט תיקייה קבועה, עם גישה ישירה למסמכים ותכניות.</p></div><div>{project.driveFolderUrl && <a className="secondary link-button" href={project.driveFolderUrl} target="_blank" rel="noreferrer"><ExternalLink /> פתיחת התיקייה</a>}<button className="primary" onClick={() => void refresh()} disabled={loading}><HardDrive /> {project.driveFolderId ? 'רענון' : 'יצירת תיקיית פרויקט'}</button></div></div>{error && <div className="error-banner">{error}</div>}<div className="drive-list">{files.map((file) => <a key={file.id} href={file.webViewLink} target="_blank" rel="noreferrer"><span className="file-icon"><FileText /></span><div><strong>{file.name}</strong><small>{file.mimeType} {file.modifiedTime ? `· ${dateLabel(file.modifiedTime)}` : ''}</small></div><ExternalLink /></a>)}{!project.driveFolderId && <EmptyState title="עדיין אין תיקיית Drive" text="לחיצה אחת תיצור תיקייה בשם הפרויקט תחת תיקיית השורש שהוגדרה במערכת." />}{project.driveFolderId && !files.length && !loading && <div className="table-empty">התיקייה מחוברת. לחצו רענון להצגת קבצים.</div>}</div></section>
}
