name = "rameng-crm"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[kv_namespaces]]
binding = "CONFIG"
id = "7676674ec22a440d8d946a8fe393775b"

[assets]
directory = "../dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]
